name: Sync with Upstream and Create PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream repository
        run: git remote add upstream https://github.com/Zed-Mod-School/mod-base-test-1.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Check for new commits
        id: check_new_commits
        run: |
          UPSTREAM_COMMITS=$(git rev-list HEAD..upstream/main --count)
          echo "Upstream commits: $UPSTREAM_COMMITS"
          if [ "$UPSTREAM_COMMITS" -eq "0" ]; then
            echo "No new commits found. Exiting."
            exit 0
          fi

      - name: Create new branch for update
        run: |
          BRANCH_NAME="sync-upstream-$(date +%Y%m%d%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          git merge upstream/main || echo "Merge conflicts detected. Resolving manually."
          git status
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Commit merge conflicts (if any)
        run: |
          git add -A || true
          git commit -m "Merge upstream changes" || echo "No changes to commit."

      - name: Push changes to new branch
        run: |
          git push origin "$BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const branch = process.env.BRANCH_NAME;
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Sync with Upstream - ${branch}`,
              head: branch,
              base: 'main',
              body: 'This PR includes updates from the upstream repository. If conflicts exist, please resolve them before merging.'
            });
            console.log(`Created PR: ${pr.html_url}`);
