name: Sync Upstream and Open PR

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync_mod_base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to detect new commits

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/Zed-Mod-School/mod-base-test-1.git
          git fetch upstream master

      - name: Check for new commits
        id: check_commits
        run: |
          UPSTREAM_BRANCH="master"
          git fetch upstream $UPSTREAM_BRANCH
          NEW_COMMITS=$(git rev-list HEAD..upstream/$UPSTREAM_BRANCH --count)

          if [ "$NEW_COMMITS" -gt 0 ]; then
            echo "New commits found: $NEW_COMMITS"
            echo "new_commits=true" >> $GITHUB_ENV
          else
            echo "No new commits."
            echo "new_commits=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request from mod-base-test-1
        if: env.new_commits == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "Zed-Mod-School/mod-base-test-1"  # Upstream repo
          branch: "master"  # Upstream branch
          base: "master"  # Your fork’s branch
          title: "Sync mod-base-test-1 changes"
          body: "This PR merges updates from the mod-base-test-1 upstream repository."
          labels: "automated PR, needs resolution"
          assignees: "Github Actions"
