name: Sync Upstream and Open PR

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to detect new commits

      - name: Set Git identity
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/Zed-Mod-School/mod-base-test-1.git
          git fetch upstream

      - name: Check for new commits
        id: check_commits
        run: |
          UPSTREAM_BRANCH="master"
          git fetch upstream $UPSTREAM_BRANCH
          NEW_COMMITS=$(git rev-list HEAD..upstream/$UPSTREAM_BRANCH --count)

          if [ "$NEW_COMMITS" -gt 0 ]; then
            echo "New commits found: $NEW_COMMITS"
            echo "new_commits=true" >> $GITHUB_ENV
          else
            echo "No new commits."
            echo "new_commits=false" >> $GITHUB_ENV
          fi

      - name: Create new branch and attempt merge
        if: env.new_commits == 'true'
        run: |
          PR_BRANCH="sync-upstream-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $PR_BRANCH
          git merge upstream/master || true  # Allow merge conflicts to exist
          git add . || true  # Stage conflicting files (GitHub will show conflicts)
          git commit -m "Attempt to merge upstream changes (conflicts may need resolution)" || true
          echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request (Even with Conflicts)
        if: env.new_commits == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Attempt to merge upstream changes (conflicts may need resolution)"
          branch: ${{ env.PR_BRANCH }}  # Let GitHub Actions create this branch
          delete-branch: true
          base: master
          title: "Sync upstream changes"
          body: "This PR attempts to merge upstream changes. **Conflicts may need manual resolution.**"
          labels: "automated PR, needs resolution"
          assignees: "Github Actions"
